/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as RolesRouteImport } from "./routes/roles";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as AnalyticsRouteImport } from "./routes/analytics";
import { Route as AlertsRouteImport } from "./routes/alerts";
import { Route as IndexRouteImport } from "./routes/index";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
});
const RolesRoute = RolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
});
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => rootRouteImport,
});
const AlertsRoute = AlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  NotificationsRoute: NotificationsRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
